title: Logstash Windows common log sources
order: 20
backends:
  - es-qs
  - es-dsl
  - kibana
  - xpack-watcher
  - elastalert
  - elastalert-dsl
logsources:
  windows:
    product: windows
    index: logstash-windows-*
  windows-application:
    product: windows
    service: application
    conditions:
      Channel: Application
  windows-security:
    product: windows
    service: security
    conditions:
      Channel: Security
  windows-sysmon:
    product: windows
    service: sysmon
    conditions:
      Channel: Microsoft-Windows-Sysmon
  windows-dns-server:
    product: windows
    service: dns-server
    conditions:
      Channel: 'DNS Server'
  windows-driver-framework:
    product: windows
    service: driver-framework
    conditions:
      Channel: 'Microsoft-Windows-DriverFrameworks-UserMode/Operational'
  windows-dhcp:
    product: windows
    service: dhcp
    conditions:
      Channel: 'Microsoft-Windows-DHCP-Server/Operational'
defaultindex: logstash-*
